name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Read changelog for current version
        id: changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'CHANGELOG.md';
            const tag = process.env.GITHUB_REF_NAME; 
            const content = fs.readFileSync(path, 'utf8');
            const regex = new RegExp(`## \\[${tag}\\](.*?)(## \\[v|$)`, 's');
            const match = content.match(regex);
            if (match) {
              const changelog = match[1].trim();
                core.setOutput('changelog', '['+process.env.GITHUB_REF_NAME+']'+changelog);
                } else {
              throw new Error(`No changelog entry found for version ${tag}`);
            }
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
