name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: bun install

      - name: Read changelog for current version
        id: changelog
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'CHANGELOG.md';
            const tag = process.env.GITHUB_REF_NAME; 
            const content = fs.readFileSync(path, 'utf8');
            const regex = new RegExp(`## \\[${tag}\\](.*?)(## \\[v|$)`, 's');
            const match = content.match(regex);
            if (match) {
              const changelog = match[1].trim();
                core.setOutput('changelog', '['+process.env.GITHUB_REF_NAME+']'+changelog);
                } else {
              throw new Error(`No changelog entry found for version ${tag}`);
            }

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseBody: ${{ steps.changelog.outputs.changelog }}
          releaseDraft: false
          prerelease: false
          tauriScript: bunx tauri
